defaults:
  - benchmark # inheriting benchmark schema
  - scenario: inference
  - launcher: process
  - backend: pytorch
  - _self_ # for hydra 1.1 compatibility

name: ontological_transformer_benchmark

launcher:
  start_method: spawn
  device_isolation: true
  device_isolation_action: warn

backend:
  device: cuda
  device_ids: 0
  no_weights: false
  model: local/ontological_transformer
  cache_implementation: static
  torch_compile: true
  torch_dtype: float16
  torch_compile_config:
    backend: inductor
    mode: reduce-overhead
    fullgraph: true

scenario:
  input_shapes:
    batch_size: 1
    sequence_length: 10
  memory: true
  latency: true
  iterations: 5
  duration: 0

# hydra/cli specific settings
hydra:
  run:
    # where to store run results
    dir: runs/${name}
  job:
    # change working directory to the run directory
    chdir: true
    env_set:
      # set environment variable OVERRIDE_BENCHMARKS to 1
      # to not skip benchmarks that have been run before
      OVERRIDE_BENCHMARKS: 1
      LOG_LEVEL: WARN
  sweep:
    dir: multirun
    subdir: ${hydra.job.override_dirname} 